analytics: {}
color:
  brandColors:
    - '#98A8B0'
    - '#283058'
    - '#B09860'
    - '#C0A068'
    - '#000000'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.71509
cta: {}
layout_spectrum: 0.569819
name: Texture Maps
opengraph: {}
purpose: {}
typography_spectrum: 0.38063
