analytics: {}
color:
  brandColors:
    - '#98A8B0'
    - '#283058'
    - '#B09860'
    - '#C0A068'
    - '#000000'
  brandStrength: 0.503378
  lightness: 0
  rhythmicContrast: 1
  saturation: 0.71509
cta: {}
layout_spectrum: 1
name: Texture Maps
opengraph: {}
purpose: {}
typography_spectrum: 0.166666
