analytics: {}
color:
  brandColors:
    - '#D0C8A8'
    - '#000000'
    - '#989860'
    - '#000000'
    - '#E0D8B8'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0.724099
  saturation: 0.318693
cta: {}
layout_spectrum: 1
name: Texture Maps
opengraph: {}
purpose: {}
typography_spectrum: 0.166666
