name: Texture Maps
favicon: null
layout_spectrum: 0.75626
typography_spectrum: 0.49571
title: skin up your renders
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98A8B0'
    - '#283058'
    - '#B09860'
    - '#C0A068'
    - '#000000'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
