analytics: {}
color:
  brandColors:
    - '#B8C0B8'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0.724099
  saturation: 0.318693
cta: {}
layout_spectrum: 0.801801
name: Texture Maps
opengraph: {}
purpose: {}
typography_spectrum: 0.166666
